##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mysql-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "3"
  priority_io: "high"
  io_profile: "db"
allowVolumeExpansion: true
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mysql-sc-aggr
provisioner: kubernetes.io/portworx-volume
parameters:
  fs: "ext4"
  block_size: "512b"
  repl: "2"
  aggregation_level: "2"
  io_profile: "random"
  priority_io: "high"
  shared: "false"
  snap_schedule: "periodic=60,5"
  labels: "type=aggregated"
  group: "mysql-data"
allowVolumeExpansion: true
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mysql-sc-seq
provisioner: kubernetes.io/portworx-volume
parameters:
  fs: "xfs"
  repl: "3"
  aggregation_level: "1"
  io_profile: "sequential"
  priority_io: "high"
  shared: "false"
  snap_schedule: "daily=12:00,7"
  labels: "type=replicated"
  group: "mysql-data"
allowVolumeExpansion: true
