##### Persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: px-nginx-pvc-legacy-shared
spec:
  storageClassName: nginx-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
