sudo: required
dist: xenial
language: go
go:
  - 1.15.x
before_install:
  - sudo apt-get update -yq
  - sudo apt-get install go-md2man -y
  - sudo apt-get install -y awscli
cache:
  directories:
    - $HOME/.cache/go-build
script:
  - |
    if [ "${TRAVIS_BRANCH}" == "2.9" ]; then
      export DOCKER_HUB_STORK_TAG="${TRAVIS_BRANCH}"-dev
      export DOCKER_HUB_STORK_TEST_TAG="${TRAVIS_BRANCH}"
      export DOCKER_HUB_CMD_EXECUTOR_TAG="${TRAVIS_BRANCH}"-dev
    else
      export DOCKER_HUB_STORK_TAG=`git rev-parse --short HEAD`
      export DOCKER_HUB_STORK_TEST_TAG=`git rev-parse --short HEAD`
      export DOCKER_HUB_CMD_EXECUTOR_TAG=`git rev-parse --short HEAD`
    fi
    make -j 2 && make test && make container && make integration-test && make integration-test-container &&
    if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      docker login -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}";
      make deploy;
      make integration-test-deploy;
    fi
notifications:
  email:
    on_success: always
    on_failure: always
after_success:
  - bash <(curl -s https://codecov.io/bash)
