sudo: required
dist: trusty
language: go
go:
  - 1.9.2
before_install:
  - sudo apt-get update -yq
  - sudo apt-get install go-md2man -y
script:
  - |
    if [ "${TRAVIS_BRANCH}" == "1.1" ]; then
      export DOCKER_HUB_STORK_TAG="${TRAVIS_BRANCH}"-dev
      export DOCKER_HUB_STORK_TEST_TAG="${TRAVIS_BRANCH}"
    else
      export DOCKER_HUB_STORK_TAG=`git rev-parse --short HEAD`
      export DOCKER_HUB_STORK_TEST_TAG=`git rev-parse --short HEAD`
    fi
    make && make pretest && make test && make container && make integration-test && make integration-test-container &&
    if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      docker login -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}";
      make deploy;
      make integration-test-deploy;
    fi
notifications:
  email:
    on_success: always
    on_failure: always
after_success:
  - bash <(curl -s https://codecov.io/bash)
