sudo: required
dist: focal
services:
  - docker
language: go
go:
  - 1.16.x
cache:
  directories:
    - $GOPATH/pkg/mod
before_install:
  - sudo apt-get update -yq
  - sudo apt-get install apt-transport-https ca-certificates -y
  - sudo update-ca-certificates
script:
  - make all
after_success:
  - if [ "${TRAVIS_BRANCH}" == "master" ] && [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      echo "${DOCKER_PASS}" | docker login -u="${DOCKER_USER}" --password-stdin;
      make container;
      sudo docker tag "${DOCKER_HUB_REPO}/torpedo:${DOCKER_HUB_TAG}" "${DOCKER_HUB_REPO}/torpedo:${TRAVIS_BRANCH}";
      sudo docker push "${DOCKER_HUB_REPO}/torpedo:${DOCKER_HUB_TAG}";
      sudo docker push "${DOCKER_HUB_REPO}/torpedo:${TRAVIS_BRANCH}";
      make container-pds;
      sudo docker tag "${DOCKER_HUB_REPO}/torpedo-pds:${DOCKER_HUB_TAG}" "${DOCKER_HUB_REPO}/torpedo-pds:${TRAVIS_BRANCH}";
      sudo docker push "${DOCKER_HUB_REPO}/torpedo-pds:${DOCKER_HUB_TAG}";
      sudo docker push "${DOCKER_HUB_REPO}/torpedo-pds:${TRAVIS_BRANCH}";
      make container-backup;
      sudo docker tag "${DOCKER_HUB_REPO}/torpedo-backup:${DOCKER_HUB_TAG}" "${DOCKER_HUB_REPO}/torpedo-backup:${TRAVIS_BRANCH}";
      sudo docker push "${DOCKER_HUB_REPO}/torpedo-backup:${DOCKER_HUB_TAG}";
      sudo docker push "${DOCKER_HUB_REPO}/torpedo-backup:${TRAVIS_BRANCH}";
    fi
notifications:
  email:
    recipients:
      - aditya@portworx.com
      - piyush@portworx.com
      - harsh@portworx.com
    on_success: change
    on_failure: always
