sudo: required
dist: trusty
language: go
go:
  - 1.11.2
before_install:
  - sudo apt-get update -yq
  - sudo apt-get install go-md2man -y
  - sudo apt-get install -y awscli
script:
  - |
    if [ "${TRAVIS_BRANCH}" == "2.0" ]; then
      export DOCKER_HUB_STORK_TAG="${TRAVIS_BRANCH}"-dev
      export DOCKER_HUB_STORK_TEST_TAG="${TRAVIS_BRANCH}"
      export DOCKER_HUB_CMD_EXECUTOR_TAG="${TRAVIS_BRANCH}"-dev
    else
      export DOCKER_HUB_STORK_TAG=`git rev-parse --short HEAD`
      export DOCKER_HUB_STORK_TEST_TAG=`git rev-parse --short HEAD`
      export DOCKER_HUB_CMD_EXECUTOR_TAG=`git rev-parse --short HEAD`
    fi
    make && make pretest && make test && make container && make integration-test && make integration-test-container &&
    if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
      docker login -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}";
      make deploy;
      make integration-test-deploy;
    fi &&
    if [ "${TRAVIS_PULL_REQUEST}" == "false" ] && [ "${TRAVIS_BRANCH}" == "2.0" ]; then
      BASE_PATH=${BUCKET_NAME}/storkctl/"${TRAVIS_BRANCH}"-dev
      aws s3 cp --acl public-read bin/linux/storkctl s3://$BASE_PATH/linux/;
      aws s3 cp --acl public-read bin/windows/storkctl.exe s3://$BASE_PATH/windows/;
      aws s3 cp --acl public-read bin/darwin/storkctl s3://$BASE_PATH/darwin/;
    fi
notifications:
  email:
    on_success: always
    on_failure: always
after_success:
  - bash <(curl -s https://codecov.io/bash)
