# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

required = [
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/gengo/args",
  "k8s.io/gengo/generator",
  "k8s.io/gengo/examples/defaulter-gen/generators",
  "k8s.io/code-generator/cmd/defaulter-gen/args",
  "k8s.io/code-generator/cmd/deepcopy-gen/args"
]

[[constraint]]
  name = "github.com/kubernetes-incubator/external-storage"
  source = "github.com/libopenstorage/external-storage"
  version = "v5.1.0-openstorage"

[[constraint]]
  name = "github.com/libopenstorage/openstorage"
  branch = "release-4.0"

[[constraint]]
  #branch = "kubernetes-1.11"
  branch = "group-snap-1.11"
  name = "github.com/portworx/sched-ops"

[[constraint]]
  name = "github.com/heptio/ark"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/skyrings/skyring-common"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.0"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.11.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.0"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.11.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "8.0.0"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "1.11.3"

[[constraint]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.11.0"

[[override]]
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

[[override]]
  name = "github.com/docker/docker"
  revision = "4f3616fb1c112e206b88cb7a9922bf49067a7756"

[[override]]
  name = "github.com/Azure/go-autorest"
  revision = "1ff28809256a84bb6966640ff3d0371af82ccba4"

[[override]]
  name = "github.com/russross/blackfriday"
  revision = "300106c228d52c8941d4b3de6054a6062a86dda3"

[prune]
  go-tests = true
  unused-packages = true

[[prune.project]]
  name = "k8s.io/code-generator"
  unused-packages = false
  go-tests = false
