##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: test-sv4-sc-svc
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "3"
  sharedv4: "true"
  sharedv4_svc_type: "ClusterIP"
allowVolumeExpansion: true
---
##### Portworx persistent volume claim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-sv4-pvc-svc
spec:
  storageClassName: test-sv4-sc-svc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi

