apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-es-sc
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Standard_LRS
  location: eastus
  storageAccount: pwxautomation