##### Azure storage class
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-sc
provisioner: disk.csi.azure.com
parameters:
  skuName: Standard_LRS
  location: eastus
  storageAccount: pwxautomation

