##### Azure storage class
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-sc
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Standard_LRS
  location: eastus
  storageAccount: pwxautomation
---
##### Azure storage class
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-sc-seq
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Standard_LRS
  location: eastus
  storageAccount: pwxautomation
---
##### Azure storage class
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysql-sc-aggr
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Standard_LRS
  location: eastus
  storageAccount: pwxautomation
