apiVersion: v1
kind: Secret
metadata:
  name: volume-secrets
type: Opaque
data:
  vdbench-secret: dmRiZW5jaCBzaGFyZWR2NCBzdmMgcm9ja3MhCg==
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vdbench-sc-sv4-svc
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "3"
  sharedv4: "true"
  mount_options: "nodiscard=true"
  sharedv4_svc_type: "ClusterIP"
allowVolumeExpansion: true
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vdbench-pvc-enc-sv4-svc
  annotations:
    px/secret-name: volume-secrets
    px/secret-namespace: "_NAMESPACE_"
    px/secret-key: vdbench-secret
    px/secure: "true"
spec:
  storageClassName: vdbench-sc-sv4-svc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vdbench-pvc-output-sv4-svc
spec:
  storageClassName: vdbench-sc-sv4-svc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
