apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: wordpress-sc-legacy-shared
provisioner: pxd.portworx.com
parameters:
  # Tests:
  # * FlashBlade Direct Access
  # * Default export rules
  backend: "pure_file"
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: wordpress-sc
provisioner: pxd.portworx.com
parameters:
  # Tests:
  # * FlashBlade Direct Access
  # * Default export rules
  backend: "pure_file"
allowVolumeExpansion: true
