apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: portworx-sc-cms-repl3-sharedv4-svc
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "3"
  priority_io: "high"
  sharedv4: "true"
  sharedv4_svc_type: "ClusterIP"
  io_profile: "cms"
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: portworx-sc-db-repl3-wp
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "3"
  io_profile: "db"
  priority_io: "high"
allowVolumeExpansion: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim-sharedv4
  labels:
    app: wordpress
  annotations:
    volume.beta.kubernetes.io/storage-class: portworx-sc-cms-repl3-sharedv4-svc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-1-wordpress
  annotations:
    volume.beta.kubernetes.io/storage-class: portworx-sc-db-repl3-wp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
