apiVersion: v1
kind: Service
metadata:
  name: nodeport
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: nodeport
      port: 27017
      protocol: TCP
      targetPort: 22
  selector:
    special: key
  type: NodePort