# Azure disk storage class
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: wordpress-sc
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Standard_LRS
  location: eastus
  storageAccount: pwxautomation
---
##### Azure file storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: wordpress-sc-shared
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
parameters:
  skuName: Standard_LRS
  location: eastus
  storageAccount: pwxautomation
