##### Portworx storage class
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nginx-sc
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "3"
  sharedv4: "true"
  secure: "true"
allowVolumeExpansion: true